# Generated by Django 2.2.7 on 2020-01-06 23:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_auto_20200102_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='day',
            field=models.CharField(default=datetime.date(2020, 1, 6), max_length=15),
        ),
    ]
